### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by zgjsyxwj** [killmymates/Pornhub#1]
import requests
from lxml import etree
import fire
拉到pyCharm里，这几个都在报错

**Comment by killmymates** [comment]
这几个都是py的第三方包 要安装的 你可以看看如何用pip安装python第三方库

**Comment by zgjsyxwj** [comment]
好的,python小白，为了pornhub决定一试 ：）

**Comment by zgjsyxwj** [comment]
下载成功了！赞一个！可惜翻墙不易。
