### ISSUE TITLE
每次只能下一个MP4文件

### ISSUE THREAD

**Issue by CNboy2018** [killmymates/Pornhub#10]
楼主！
download.txt文件里面已经添加很多条后缀了，但是每次运行python crawler.py run mp4之后就只下载了一个MP4视频，运行这个命令的窗口下了一个文件之后就一直在等待，附件是截图
![2](https://user-images.githubusercontent.com/38393178/38852483-a7f89f7e-424c-11e8-9a00-06a1aa5612ce.png)
![1](https://user-images.githubusercontent.com/38393178/38852493-afb91702-424c-11e8-935c-6aa82c51a72f.png)

**Comment by killmymates** [comment]
是这个样子的 我加了gevent 以为可以用协程多个一起下载 然并卵
