### ISSUE TITLE
不太懂下载地址是怎么解析出来的

### ISSUE THREAD

**Issue by Wangjinqian** [killmymates/Pornhub#12]
抱着学习的目的（滑稽）楼主想要搞清楚是如何通过detial_page获得下载地址的，下载地址在解析的页面中找不到啊

**Comment by killmymates** [comment]
下载的地址在页面的js里，我是通过正则匹配出来的

    js = html.xpath('//*[@id="player"]/script/text()')[0]
    tem = re.findall('var\\s+\\w+\\s+=\\s+(.*);\\s+var player_mp4_seek', js)[-1]
    con = json.loads(tem)
