### ISSUE TITLE
Invalid address

### ISSUE THREAD

**Issue by cobbwho** [killmymates/Pornhub#13]
I read your program “crawler.py”. In line 55 ,I also got the variable "videoUrl" by check web page source code. But when i go to this video connection in my browser, there is a problem "403 forbidden" and no video appeared. Is the argument or encrypted address passed in the get or post method? How do you do it to get the video. Where is the relevant code? In fact this is not a strict issue, you can close it ,if you wantted. Thanks.

**Comment by killmymates** [comment]
show your url

**Comment by cobbwho** [comment]
I finally found the reason and thank you for your reply. The video url address written in your program and the address I got were all correct. Just because Firefox has video encoding issues, it cannot be displayed(Dialog Box Tip: No supported video formats and mime types were found). I downloaded video from the url address after I entered it into the download tool. Finally, thank you for your reply.
