### ISSUE TITLE
如何选择分辨率>提示'module' object has no attribute 'request'

### ISSUE THREAD

**Issue by rokycool** [killmymates/Pornhub#2]
非常感谢你的开发

提示'module' object has no attribute 'request'

终端显示：
ython crawler.py run mp4
https://www.pornhub.com/view_video.php?viewkey=ph5a329fa707269
(u'720', u'https://cv.phncdn.com/videos/201712/14/145435922/720P_1500K_145435922.mp4?a5dcae8e1adc0bdaed975f0d67fb5e0527c20903c5bb57a6cad7e6cb50bc41fbb1152c24e90ee00089707ead83a48b070c589981d38ac6814e90e9027c5fef49530c1d15171eb4cc933256dcb20f12cf41c98221a8dd2c25f6a4761c02801426a5d6e04224d1557291a7a809c5edb858e1397be19fb5d019fb585ca3')
'module' object has no attribute 'request'
(u'480', u'https://cv.phncdn.com/videos/201712/14/145435922/480P_600K_145435922.mp4?a5dcae8e1adc0bdaed975f0d60fb5e050d523df0cca6435032db1bab0a4b451d8a412585437d61afcbe65f741a8e73018788967486d8fc8cd54973b85680105d1c516cef5a48006e1c2a9ab15a0d755f2e3f5e6369ad554879e75b3c68c0dd35f4ef7f0ae8ca61cde980f515593d4cb6efc17d358f5054ec6f14fa')
'module' object has no attribute 'request'
(u'240', u'https://cv.phncdn.com/videos/201712/14/145435922/240P_400K_145435922.mp4?a5dcae8e1adc0bdaed975f0d60fb5e050d523df0cca6435032db1bab0a4b451d8a412585437d61afcbe65f741a8e73018788967486d8fc8abad414435d75d80c1f5533c135e7fef4eb583ad52c64c3cce61e6535ef4326f310b2dfc96a108b8a992a4585d9cf27cb2d7358b66ff49b8a8ed1141e1ce1f66081c89b')
'module' object has no attribute 'request'
finish !

google后打算 crawler.py中在开头的import urllib改为import urllib.request
但是运行后报错 ImportError: No module named requests

**Comment by killmymates** [comment]
装一个py3的虚拟环境

**Comment by KevinAndrewDong** [comment]
pip install requests解决。推荐pythoncharm管理模块。
