### ISSUE TITLE
运行后仅显示如下代码后结束？

### ISSUE THREAD

**Issue by Holo233** [killmymates/Pornhub#4]
os:          <module 'os' from 'F:\\Python\\lib\\os.py'>
urllib:      <module 'urllib' from 'F:\\Python\\lib\\urllib\\__init__.py'>
json:        <module 'json' from 'F:\\Python\\lib\\json\\__init__.py'>
re:          <module 're' from 'F:\\Python\\lib\\re.py'>
gevent:      <module 'gevent' from 'F:\\Python\\lib\\site-packages\\gevent\\__init__.py'>
requests:    <module 'requests' from 'F:\\Python\\lib\\site-packages\\requests\\__init__.py'>
etree:       <module 'lxml.etree' from 'F:\\Python\\lib\\site-packages\\lxml\\etree.cp36-win_amd64.pyd'>
fire:        <module 'fire' from 'F:\\Python\\lib\\site-packages\\fire\\__init__.py'>
headers:     {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"}
list_page:   <function list_page at 0x0000020235A12E18>
detail_page: <function detail_page at 0x0000020236DCD378>
download:    <function download at 0x0000020236E48620>
run:         <function run at 0x0000020236E486A8>

**Comment by killmymates** [comment]
请阅读README.md文件

**Comment by Holo233** [comment]
不好意思，小白一枚，readme中不是指运行crawler.py文件吗？或者我理解错了？麻烦指教一下

**Comment by killmymates** [comment]
![1517823398718](https://user-images.githubusercontent.com/17539640/35797627-390f6d88-0a9b-11e8-8b8f-1f38569ee943.jpg)
